from __future__ import annotations

import uuid
from datetime import datetime
from typing import Protocol, Sequence

from mvpauth.core.schemas import UserData, SessionData


class UserRepository(Protocol):
    async def create(self, *, email: str, hashed_password: str) -> UserData: ...
    async def get_by_id(self, user_id: uuid.UUID) -> UserData | None: ...
    async def get_by_email(self, email: str) -> UserData | None: ...
    async def update(self, user_id: uuid.UUID, **fields: object) -> UserData: ...
    async def delete(self, user_id: uuid.UUID) -> None: ...


class SessionRepository(Protocol):
    async def create(
        self,
        *,
        user_id: uuid.UUID,
        refresh_token_hash: str,
        device_info: str | None = None,
        ip_address: str | None = None,
        expires_at: datetime,
    ) -> SessionData: ...

    async def get_by_id(self, session_id: uuid.UUID) -> SessionData | None: ...
    async def get_active_by_user(self, user_id: uuid.UUID) -> Sequence[SessionData]: ...
    async def revoke(self, session_id: uuid.UUID) -> None: ...
    async def revoke_all_for_user(self, user_id: uuid.UUID) -> int: ...
    async def update_refresh_token(
        self,
        session_id: uuid.UUID,
        *,
        new_refresh_token_hash: str,
        new_expires_at: datetime,
    ) -> SessionData: ...


class TokenBlocklistRepository(Protocol):
    async def add(self, *, jti: str, token_type: str, expires_at: datetime) -> None: ...
    async def is_blocked(self, jti: str) -> bool: ...
    async def purge_expired(self) -> int: ...


class StorageBackend(Protocol):
    @property
    def user_repo(self) -> UserRepository: ...
    @property
    def session_repo(self) -> SessionRepository: ...
    @property
    def blocklist_repo(self) -> TokenBlocklistRepository: ...
